python 2.4

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2350,9 +2350,50 @@ echo "${ECHO_T}no" >&6
 fi
 
   if test -z "$PYTHON_BIN"; then
-    { { echo "$as_me:$LINENO: error: python binary not found in path" >&5
+    # Extract the first word of "python2.4", so it can be a program name with args.
+set dummy python2.4; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_PYTHON_BIN+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PYTHON_BIN in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PYTHON_BIN="$PYTHON_BIN" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_PYTHON_BIN="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+PYTHON_BIN=$ac_cv_path_PYTHON_BIN
+
+if test -n "$PYTHON_BIN"; then
+  echo "$as_me:$LINENO: result: $PYTHON_BIN" >&5
+echo "${ECHO_T}$PYTHON_BIN" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+    if test -z "$PYTHON_BIN"; then
+       { { echo "$as_me:$LINENO: error: python binary not found in path" >&5
 echo "$as_me: error: python binary not found in path" >&2;}
    { (exit 1); exit 1; }; }
+    fi
   fi
 fi
 
@@ -2369,9 +2410,11 @@ echo "${ECHO_T}$PyVERSION, fantastic." >&6
 # make sure Python is version 2
 
 if test "$PyVERSION" != "2.3"; then
-  { { echo "$as_me:$LINENO: error: This version of only works with Python version 2.3. The one you have seems to be $PyVERSION." >&5
-echo "$as_me: error: This version of only works with Python version 2.3. The one you have seems to be $PyVERSION." >&2;}
+   if test "$PyVERSION" != "2.4"; then
+      { { echo "$as_me:$LINENO: error: This version of only works with Python version 2.3 or 2.4. The one you have seems to be $PyVERSION." >&5
+echo "$as_me: error: This version of only works with Python version 2.3 or 2.4. The one you have seems to be $PyVERSION." >&2;}
    { (exit 1); exit 1; }; }
+   fi
 fi
 
 # check for apxs
