ovwrapper and other stuff

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -271,7 +271,7 @@ PACKAGE_VERSION=
 PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA SET_MAKE PYTHON_BIN PYTHON APXS VDLIMIT_DIR RRDTOOL NAMED OHD_USER OHD_PORT LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA SET_MAKE PYTHON_BIN PYTHON APXS VDLIMIT_DIR RRDTOOL VSERVER NAMED OHD_USER OHD_PORT LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -2418,8 +2418,8 @@ echo "${ECHO_T}no" >&6
 fi
 
 if test -n "$APXS"; then
-  echo "$as_me:$LINENO: result: found $APXS, good, assuming httpd is installed." >&5
-echo "${ECHO_T}found $APXS, good, assuming httpd is installed." >&6
+  echo "$as_me:$LINENO: result: found $APXS, outstanding, assuming httpd is installed." >&5
+echo "${ECHO_T}found $APXS, outstanding, assuming httpd is installed." >&6
 fi
 
 if test -z "$APXS"; then
@@ -2537,6 +2537,59 @@ else
 echo "${ECHO_T}$VS, looks like a vserver kernel." >&6
 fi
 
+# check for vserver from util-vserver
+
+#AC_CHECKING(whether vserver command is available)
+# Extract the first word of "vserver", so it can be a program name with args.
+set dummy vserver; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_VSERVER+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $VSERVER in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_VSERVER="$VSERVER" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_VSERVER="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+VSERVER=$ac_cv_path_VSERVER
+
+if test -n "$VSERVER"; then
+  echo "$as_me:$LINENO: result: $VSERVER" >&5
+echo "${ECHO_T}$VSERVER" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+if test -n "$VSERVER"; then
+  echo "$as_me:$LINENO: result: found $VSERVER, cool." >&5
+echo "${ECHO_T}found $VSERVER, cool." >&6
+fi
+
+if test -z "$VSERVER"; then
+  { { echo "$as_me:$LINENO: error: not found. This means util-vserver probably is not installed" >&5
+echo "$as_me: error: not found. This means util-vserver probably is not installed" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 # check for bind
 
 # Extract the first word of "named", so it can be a program name with args.
@@ -2592,7 +2645,7 @@ OHD_PORT="1012"
 
 # final output
 
-                                                                                                                                                                                    ac_config_files="$ac_config_files Makefile scripts/Makefile src/Makefile rhinit/Makefile mkspec rhinit/ohd rhinit/openvps-mon crontab/Makefile crontab/openvps src/ohchkpwd/Makefile www/Makefile www/conf/Makefile lib/python/oh/host/dft.py openvps.conf ohd/Makefile ohd/common.h ohd/sshd_config src/pace/Makefile"
+                                                                                                                                                                                                        ac_config_files="$ac_config_files Makefile scripts/Makefile src/Makefile rhinit/Makefile mkspec rhinit/ohd rhinit/openvps-mon crontab/Makefile crontab/openvps src/ohchkpwd/Makefile www/Makefile www/conf/Makefile lib/python/oh/host/dft.py openvps.conf ohd/Makefile ohd/common.h ohd/sshd_config src/pace/Makefile src/wrapper/wrapper.h src/wrapper/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -3162,6 +3215,8 @@ do
   "ohd/common.h" ) CONFIG_FILES="$CONFIG_FILES ohd/common.h" ;;
   "ohd/sshd_config" ) CONFIG_FILES="$CONFIG_FILES ohd/sshd_config" ;;
   "src/pace/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/pace/Makefile" ;;
+  "src/wrapper/wrapper.h" ) CONFIG_FILES="$CONFIG_FILES src/wrapper/wrapper.h" ;;
+  "src/wrapper/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/wrapper/Makefile" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
@@ -3261,6 +3316,7 @@ s,@PYTHON@,$PYTHON,;t t
 s,@APXS@,$APXS,;t t
 s,@VDLIMIT_DIR@,$VDLIMIT_DIR,;t t
 s,@RRDTOOL@,$RRDTOOL,;t t
+s,@VSERVER@,$VSERVER,;t t
 s,@NAMED@,$NAMED,;t t
 s,@OHD_USER@,$OHD_USER,;t t
 s,@OHD_PORT@,$OHD_PORT,;t t
