now we rely on vdlimit rpm like we should

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -271,7 +271,7 @@ PACKAGE_VERSION=
 PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA SET_MAKE PYTHON_BIN PYTHON APXS VDLIMIT_DIR RRDTOOL VSERVER NAMED OHD_USER OHD_PORT LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA SET_MAKE PYTHON_BIN PYTHON APXS VDLIMIT RRDTOOL VSERVER NAMED OHD_USER OHD_PORT LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -2464,16 +2464,55 @@ fi
 
 # check for vdlimit
 
-
-VDLIMIT_DIR=/usr/local/vdlimit-0.01
-echo "$as_me:$LINENO: checking for vdlimit in $VDLIMIT_DIR" >&5
-echo $ECHO_N "checking for vdlimit in $VDLIMIT_DIR... $ECHO_C" >&6
-if test -x "$VDLIMIT_DIR/vdlimit"; then
-  echo "$as_me:$LINENO: result: found, excellent." >&5
-echo "${ECHO_T}found, excellent." >&6
+{ echo "$as_me:$LINENO: checking whether vdlimit is available..." >&5
+echo "$as_me: checking whether vdlimit is available..." >&6;}
+# Extract the first word of "vdlimit", so it can be a program name with args.
+set dummy vdlimit; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_VDLIMIT+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  { { echo "$as_me:$LINENO: error: vdlimit not found. You need to place vdlimit in $VDLIMIT_DIR" >&5
-echo "$as_me: error: vdlimit not found. You need to place vdlimit in $VDLIMIT_DIR" >&2;}
+  case $VDLIMIT in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_VDLIMIT="$VDLIMIT" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_VDLIMIT="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+VDLIMIT=$ac_cv_path_VDLIMIT
+
+if test -n "$VDLIMIT"; then
+  echo "$as_me:$LINENO: result: $VDLIMIT" >&5
+echo "${ECHO_T}$VDLIMIT" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+if test -n "$VDLIMIT"; then
+  echo "$as_me:$LINENO: result: found $VDLIMIT, nice." >&5
+echo "${ECHO_T}found $VDLIMIT, nice." >&6
+fi
+
+if test -z "$VDLIMIT"; then
+  { { echo "$as_me:$LINENO: error: vdlimit not found. You need to place vdlimit in your path." >&5
+echo "$as_me: error: vdlimit not found. You need to place vdlimit in your path." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -3317,7 +3356,7 @@ s,@SET_MAKE@,$SET_MAKE,;t t
 s,@PYTHON_BIN@,$PYTHON_BIN,;t t
 s,@PYTHON@,$PYTHON,;t t
 s,@APXS@,$APXS,;t t
-s,@VDLIMIT_DIR@,$VDLIMIT_DIR,;t t
+s,@VDLIMIT@,$VDLIMIT,;t t
 s,@RRDTOOL@,$RRDTOOL,;t t
 s,@VSERVER@,$VSERVER,;t t
 s,@NAMED@,$NAMED,;t t
